### ISSUE TITLE
version 1.1.0: API-Key not stored

### ISSUE THREAD

**Issue by latzi0710** [klein0r/ioBroker.octoprint#47] opened 2021-05-05 08:48 UTC
With adapter version 1.1.0 the API-Key is not stored permanently. When stoping and restarting it, following error message comes up: "Invalid value "undefined" for header "X-Api-Key" and the API-Key field is empty again.

**Comment by klein0r** [comment] 2021-05-05 08:50
Duplicate of #45

**Closed by klein0r** 2021-05-05 08:50 UTC
